alarmLabel = "BallerinaMailAlaram"
alarmFrom = "ballerina.mail.alaram@email.com"

smtpPort = 465
smtpServer = "smtp.gmail.com"
smtpServerLogin = "abc@email.com"
smtpServerPassword = ""

[[ccuser]]
username = "user1"
email = "user2@email.com"

[[ccuser]]
username = "user2"
email = "user2@email.com"