[[dependency]]
org = "ballerina"
name = "email"
version = "1.1.0-alpha5"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.0.0-alpha5"

[[dependency]]
org = "ballerina"
name = "observe"
version = "0.9.0"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-alpha5"

[[dependency]]
org = "ballerina"
name = "test"
version = "0.0.0"

[[dependency]]
org = "ballerina"
name = "task"
version = "2.0.0-alpha5"


